# -*- coding: utf-8 -*-
"""Process

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14pV7HPZY4tLFAsLHBs_Tk4hbmpbAdEHz
"""

import pandas as pd

!git clone https://github.com/Rising-Stars-by-Sunshine/STATS201_Yiming_Research-Proposal.git

"""Importing & showcasing the data"""

df = pd.read_csv('https://raw.githubusercontent.com/Rising-Stars-by-Sunshine/STATS201_Yiming_Research-Proposal/main/data/processed%20data/global_data_on_sustainable_energy.csv')
df

df.info()

# Assuming 'data' is your DataFrame
for column in df.columns:
    if df[column].dtype == 'object':
        try:
            # Remove commas and convert to float
            df[column] = df[column].str.replace(',', '').astype(float)
        except ValueError:
            # If conversion fails, it's not a numerical column, so do nothing
            pass
df

df.info()

df.describe().T

#rename CO2
df.rename(columns={"Value_co2_emissions_kt_by_country":"CO2" , 'Land Area(Km2)':'Land'} , inplace=True)
df

#Data cleaning
df.dropna(subset=['Entity', 'Year'], inplace=True)  # Remove rows with missing 'Entity' or 'Year'
df.fillna(0, inplace=True)  # Fill other missing values with 0, you can adapt this based on the context
df